import { GameSessionState } from './types';

export const INITIAL_STATE: GameSessionState = {
  campaign: null,
  scenes: [],
  activeSceneId: '',
  combat: null,
  players: [],
  campaignCharacters: [],
  chatMessages: [],
  handouts: [],
  templates: [],
  viewport: { x: 0, y: 0, zoom: 1 },
  isGM: false,
  gmViewMode: 'gm',
  previewPlayerId: 'all',
  activeTool: 'select',
  selectedTokenIds: [],
  movementPath: [],
  drawingObstacle: null,
  drawingLightZone: null,
  drawingAudioZone: null,
  drawingTriggerZone: null,
  draftPolyPoints: [],
  drawingSettings: { color: '#ffffff', width: 3, opacity: 1.0 },
  rulerSettings: { snapToGrid: true, metric: 'chebyshev' },
  wandSettings: { tolerance: 40, resolution: 512, simplification: 2.0, smoothing: true, smoothingIterations: 2 },
  pings: [],
  remoteDrags: {},
  remoteCursors: {},
  remoteViewports: {},
  isConnected: false,
  isLoading: true,
  // Settings
  cursorSettings: { color: '#fbbf24', name: '' },
  permissions: {
    tokenMovement: true,
    tokenHover: {
      enabled: true,
      pc: { showName: true, showHP: true, showResource: true, showConditions: true, showStats: false, showAttributes: false },
      npc: { showName: true, showHP: false, showResource: false, showConditions: true, showStats: false, showAttributes: false },
      object: { showName: true, showConditions: true }
    },
    doorControl: true,
    drawings: true,
    drawingDelete: false,
    drawingClear: false,
    measure: true,
    pingMap: true,
    diceRolling: true,
    tokenCreate: false,
    tokenEdit: false,
    tokenDelete: false,
    fogReveal: false,
    compendiumBrowse: false, // GM only by default
    bestiaryBrowse: false,
    journalCreate: true,
    sheetEdit: true,
    initiativeRoll: true,
    attackZoneCreate: false, // Criar zonas customizadas restrito ao GM
    attackZoneUse: true,     // Jogadores podem usar templates
    cursorAllowColorChange: true,
    cursorAllowShapeChange: true,
    cursorAllowNameChange: true,
    cursorAllowAnimationChange: true,
    cursorAllowAnimationColorChange: true,
    cursorAllowTrailChange: true,
    cursorOverrides: {},
    chatGlobalAllowed: true,
    chatPrivateAllowed: true,
    shareCursor: true,
    allowSpectate: true,
    logConfig: { movement: 'public', combat: 'public', rolls: 'public', system: 'public', broadcastConditions: true },
    userOverrides: {},
    showRemoteViewports: false, // Default false, GM moves toggle to enable
    shareViewport: true         // Default true, you are visible unless you hide
  },
  audioSettings: { playlists: [], soundboard: [] },
  activeAudioZoneUrl: null,
  followMode: { active: false, targets: [] },
  triggeredHandoutId: null,
  lastTriggeredZoneId: null,
  pullNotification: false,
  ui: {
    isRightSidebarOpen: true,
    isLibraryOpen: false,
    isDiceRollerOpen: false,
    isAudioPanelOpen: false,
    gmHideObstacles: false,
    showVisionRanges: false,
    showGridCoordinates: false,
    defaultObstacleHidden: false,
    isSFXPanelOpen: false
  },

  // Attack Zones (ephemeral)
  attackZones: []
};
