import { GameSessionState } from './types';

export const INITIAL_STATE: GameSessionState = {
  campaign: null,
  scenes: [],
  activeSceneId: '',
  combat: null,
  players: [],
  campaignCharacters: [],
  chatMessages: [],
  handouts: [],
  templates: [],
  viewport: { x: 0, y: 0, zoom: 1 },
  isGM: false,
  gmViewMode: 'gm',
  previewPlayerId: 'all',
  activeTool: 'select',
  selectedTokenIds: [],
  movementPath: [],
  drawingObstacle: null,
  drawingLightZone: null,
  drawingAudioZone: null,
  drawingTriggerZone: null,
  draftPolyPoints: [],
  drawingSettings: { color: '#ffffff', width: 3, opacity: 1.0 },
  rulerSettings: { snapToGrid: true, metric: 'chebyshev' },
  pings: [],
  remoteDrags: {},
  remoteCursors: {},
  isConnected: false,
  isLoading: true,
  permissions: {
    tokenMovement: true,
    doorControl: true,
    drawings: true,
    drawingDelete: false,
    drawingClear: false,
    measure: true,
    pingMap: true,
    diceRolling: true,
    tokenCreate: false,
    tokenEdit: false,
    tokenDelete: false,
    fogReveal: false,
    compendiumBrowse: true,
    journalCreate: true,
    sheetEdit: true,
    initiativeRoll: true,
    shareCursor: true,
    allowSpectate: true,
    logConfig: { movement: 'public', combat: 'public', rolls: 'public', system: 'public' },
    userOverrides: {}
  },
  audioSettings: { playlists: [], soundboard: [] },
  activeAudioZoneUrl: null,
  triggeredHandoutId: null,
  lastTriggeredZoneId: null,
  ui: {
    isRightSidebarOpen: true,
    isLibraryOpen: false,
    isDiceRollerOpen: false,
    isAudioPanelOpen: false,
    gmHideObstacles: false,
    showVisionRanges: false,
    defaultObstacleHidden: false
  }
};
