import { Point } from '../../../types';
import { OptimizationOptions } from '../types';

/**
 * Polygon simplification and smoothing
 */
export class PolygonOptimizer {
  /**
   * Calculates the squared Euclidean distance between two points.
   */
  private static distanceSquared(p1: Point, p2: Point): number {
    const dx = p1.x - p2.x;
    const dy = p1.y - p2.y;
    return dx * dx + dy * dy;
  }

  /**
   * Remove duplicate points
   */
  static removeDuplicates(
    points: Point[],
    minDistance: number = 1
  ): Point[] {
    if (points.length < 2) return points;

    const result: Point[] = [points[0]];
    const minDistSq = this.distanceSquared({ x: 0, y: 0 }, { x: minDistance, y: 0 });

    for (let i = 1; i < points.length; i++) {
      const prev = result[result.length - 1];
      const curr = points[i];
      const distSq = this.distanceSquared(prev, curr);

      if (distSq >= minDistSq) {
        result.push(curr);
      }
    }

    // Check if last point too close to first (for closed polygons)
    if (result.length > 2) {
      const distSq = this.distanceSquared(result[0], result[result.length - 1]);
      if (distSq < minDistSq) {
        result.pop();
      }
    }

    return result;
  }

  /**
   * Remove collinear points
   */
  static removeCollinear(
    points: Point[],
    angleThreshold: number = 0.05 // ~3 degrees
  ): Point[] {
    if (points.length < 3) return points;

    const result: Point[] = [points[0]];

    for (let i = 1; i < points.length - 1; i++) {
      const prev = result[result.length - 1];
      const curr = points[i];
      const next = points[i + 1];

      // Calculate angles of segments
      const angle1 = Math.atan2(curr.y - prev.y, curr.x - prev.x);
      const angle2 = Math.atan2(next.y - curr.y, next.x - curr.x);

      // Normalize angle difference to [-PI, PI]
      let angleDiff = angle2 - angle1;
      while (angleDiff > Math.PI) angleDiff -= 2 * Math.PI;
      while (angleDiff < -Math.PI) angleDiff += 2 * Math.PI;

      // Keep point only if there's a significant direction change
      if (Math.abs(angleDiff) > angleThreshold) {
        result.push(curr);
      }
    }

    // Always keep the last point
    result.push(points[points.length - 1]);

    return result;
  }

  /**
   * Ramer-Douglas-Peucker simplification
   */
  static simplifyRDP(points: Point[], epsilon: number): Point[] {
    if (points.length < 3) return points;

    let dmax = 0;
    let index = 0;
    const end = points.length - 1;

    // Find the point with the maximum distance
    for (let i = 1; i < end; i++) {
      const d = this.perpendicularDistance(points[i], points[0], points[end]);
      if (d > dmax) {
        index = i;
        dmax = d;
      }
    }

    // If max distance is greater than epsilon, recursively simplify
    if (dmax > epsilon) {
      const recResults1 = this.simplifyRDP(points.slice(0, index + 1), epsilon);
      const recResults2 = this.simplifyRDP(points.slice(index, end + 1), epsilon);
      // Concatenate results, removing the duplicate point at the join
      return [...recResults1.slice(0, recResults1.length - 1), ...recResults2];
    } else {
      // Otherwise, return only the start and end points
      return [points[0], points[end]];
    }
  }

  /**
   * Calculates the perpendicular distance of a point to a line segment.
   */
  private static perpendicularDistance(p: Point, p1: Point, p2: Point): number {
    const dx = p2.x - p1.x;
    const dy = p2.y - p1.y;

    if (dx === 0 && dy === 0) {
      return Math.hypot(p.x - p1.x, p.y - p1.y);
    }

    const mag = Math.hypot(dx, dy);
    return Math.abs(dy * p.x - dx * p.y + p2.x * p1.y - p2.y * p1.x) / mag;
  }

  /**
   * Chaikin's Corner Cutting Algorithm for smoothing
   */
  static smoothChaikin(points: Point[], iterations: number = 2, closed: boolean = true): Point[] {
    if (points.length < 3 || iterations <= 0) return points;

    let result = points;

    for (let iter = 0; iter < iterations; iter++) {
      const smoothed: Point[] = [];
      const len = result.length;

      for (let i = 0; i < len; i++) {
        const p0 = result[i];
        const p1 = result[(i + 1) % len];

        // Chaikin's ratios: 0.75/0.25 and 0.25/0.75
        const q: Point = {
          x: 0.75 * p0.x + 0.25 * p1.x,
          y: 0.75 * p0.y + 0.25 * p1.y,
        };
        const r: Point = {
          x: 0.25 * p0.x + 0.75 * p1.x,
          y: 0.25 * p0.y + 0.75 * p1.y,
        };

        smoothed.push(q, r);
      }

      // Handle open polygons by removing the extra points at the ends
      if (!closed && smoothed.length > 0) {
        // Remove the first Q and last R point generated by the loop
        smoothed.shift();
        smoothed.pop();
        // Re-add the original start and end points
        smoothed.unshift(result[0]);
        smoothed.push(result[result.length - 1]);
      }

      result = smoothed;
    }

    return result;
  }

  /**
   * Optimized contour processing pipeline
   */
  static optimizeContour(
    points: Point[],
    options: OptimizationOptions = {}
  ): Point[] {
    const {
      minPointDistance = 2,
      collinearThreshold = 0.1,
      simplifyEpsilon = 3,
      smoothIterations = 1
    } = options;

    if (points.length < 3) return points;

    // Step 1: Remove near-duplicate points
    let result = PolygonOptimizer.removeDuplicates(points, minPointDistance);

    // Step 2: Remove collinear points (straight line optimization)
    result = PolygonOptimizer.removeCollinear(result, collinearThreshold);

    // Step 3: RDP simplification for remaining curves
    result = PolygonOptimizer.simplifyRDP(result, simplifyEpsilon);

    // Step 4: Light smoothing to soften corners (assuming closed contour)
    if (smoothIterations > 0) {
      result = PolygonOptimizer.smoothChaikin(result, smoothIterations, true);
    }

    // Step 5: Final cleanup - remove any new duplicates created by smoothing
    result = PolygonOptimizer.removeDuplicates(result, minPointDistance);

    return result;
  }
}
